In [45]:
import numpy as np
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
train_data=np.loadtxt("/Users/additipandey/Downloads/0000000000002419_training_ccpp_x_y_train.csv", delimiter =",")
data=scaler.fit_transform(train_data)
test_data=np.loadtxt("/Users/additipandey/Downloads/0000000000002419_test_ccpp_x_test.csv", delimiter=",")



(7176, 4) (7176,)


In [32]:
def step_gradient(points, lr, m, c):
    m_slope=0
    c_slope=0
    for i in range(len(points)):
        x=points[i,:4]
        y=points[i,4]
        m_slope+=(-2/len(points))*(y-m*x-c)*x
        c_slope+=(-2/len(points))*(y-m*x-c)
    new_m=m-lr*m_slope
    new_c=c-lr*c_slope
    return new_m,new_c

In [15]:
def gradient(points,lr,num_iter):
    m=0
    c=0
    for i in range(num_iter):
        m,c=step_gradient(points,lr,m,c)
    return m,c

In [33]:
def cost(points,m,c):
    total_cost=0
    for i in range(len(points)):
        x=points[i,:4]
        y=points[i,4]
        total_cost+=(-2/len(points))*((y-m*x-c)**2)
    return total_cost

In [46]:

points=data
lr=0.001
num_iter=1000
m,c=gradient(points,lr,num_iter)
print(m.shape,c.shape)

(4,) (4,)


In [57]:
test_scaled = scaler.fit_transform(test_data)
tc=cost(data,m,c)
print(tc)
np.set_printoptions(precision=6)
y_pred=m*test_scaled+c
print(y_pred)
np.savetxt("predictccp.csv", y_pred, delimiter=",")


[-0.233679 -0.515114 -1.469295 -1.696756]
[[ 0.862848  0.73737   0.332487  0.409094]
 [ 0.849515  0.963447 -0.044294  0.193098]
 [-0.799341 -1.233933 -0.583758  0.130382]
 ...
 [-0.511569 -0.711203 -0.319014  0.432496]
 [-0.419348  0.691317  0.054697 -0.189516]
 [-0.22713  -0.353545  0.438384  0.272664]]


OSError: [Errno 30] Read-only file system: 'predictccp.csv'

In [56]:
from sklearn.ensemble import GradientBoostingRegressor
x = data[:,:data.shape[1]-1]
y = data[:,data.shape[1]-1]
reg = GradientBoostingRegressor()
reg.fit(x,y)
y_predict = reg.predict(test_scaled)
print(y_predict)
# np.savetxt("predictedCCP.csv", y_predict, delimiter=',')

[ 0.952978  1.064103 -1.117914 ... -0.917045 -0.087876 -0.544652]
